// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCUL_-T-6JNqjiNCksucwVtXd1Km4iPjYI',
    appId: '1:244206081755:web:da963273fa69d13dcd9efe',
    messagingSenderId: '244206081755',
    projectId: 'student-data-407b5',
    authDomain: 'student-data-407b5.firebaseapp.com',
    storageBucket: 'student-data-407b5.firebasestorage.app',
    measurementId: 'G-LWKKCZD01H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDkl79GJVBQoOk14gf1jYYc8uv5zssgSPA',
    appId: '1:244206081755:android:4b422325730cc35acd9efe',
    messagingSenderId: '244206081755',
    projectId: 'student-data-407b5',
    storageBucket: 'student-data-407b5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC4WBA9Vz1p-yyrH9x4pToEoIxCkGTWr7g',
    appId: '1:244206081755:ios:708f593976ebe499cd9efe',
    messagingSenderId: '244206081755',
    projectId: 'student-data-407b5',
    storageBucket: 'student-data-407b5.firebasestorage.app',
    iosBundleId: 'com.example.universityApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC4WBA9Vz1p-yyrH9x4pToEoIxCkGTWr7g',
    appId: '1:244206081755:ios:708f593976ebe499cd9efe',
    messagingSenderId: '244206081755',
    projectId: 'student-data-407b5',
    storageBucket: 'student-data-407b5.firebasestorage.app',
    iosBundleId: 'com.example.universityApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCUL_-T-6JNqjiNCksucwVtXd1Km4iPjYI',
    appId: '1:244206081755:web:041ccc83a02c0576cd9efe',
    messagingSenderId: '244206081755',
    projectId: 'student-data-407b5',
    authDomain: 'student-data-407b5.firebaseapp.com',
    storageBucket: 'student-data-407b5.firebasestorage.app',
    measurementId: 'G-PJ6N0ZQ385',
  );
}
